---
- name: Create ClickHouse configuration file
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.xml"
    owner: root
    group: root
    mode: '0664'

- name: Define CH log level
  template:
    src: log-level.xml.j2
    dest: "{{ clickhouse_logs_conf }}"
    mode: '0444'
  notify: Restart ClickHouse
